// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// MAIN
export const PIPELINES_LOADING = 'PIPELINES_LOADING';
export const PIPELINES_FAILED = 'PIPELINES_FAILED';
export const REQUESTS_LOADING = 'REQUESTS_LOADING';
export const REQUESTS_FAILED = 'REQUESTS_FAILED';
export const ACCEPTANCES_LOADING = 'ACCEPTANCES_LOADING';
export const ACCEPTANCES_FAILED = 'ACCEPTANCES_FAILED';
export const PROPOSALS_LOADING = 'PROPOSALS_LOADING';
export const PROPOSALS_FAILED = 'PROPOSALS_FAILED';
export const PROSPECTS_LOADING = 'PROSPECTS_LOADING';
export const PROSPECTS_FAILED = 'PROSPECTS_FAILED';
export const RENEWALS_LOADING = 'RENEWALS_LOADING';
export const RENEWALS_FAILED = 'RENEWALS_FAILED';
export const RELEASES_LOADING = 'RELEASES_LOADING';
export const RELEASES_FAILED = 'RELEASES_FAILED';
export const PLACINGS_LOADING = 'PLACINGS_LOADING';
export const PLACINGS_FAILED = 'PLACINGS_FAILED';
export const QUOTATIONS_LOADING = 'QUOTATIONS_LOADING';
export const QUOTATIONS_FAILED = 'QUOTATIONS_FAILED';
export const REIMBURSEMENTS_LOADING = 'REIMBURSEMENTS_LOADING';
export const REIMBURSEMENTS_FAILED = 'REIMBURSEMENTS_FAILED';
export const CASHLESSES_LOADING = 'CASHLESSES_LOADING';
export const CASHLESSES_FAILED = 'CASHLESSES_FAILED';