// FORM VALIDATION
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const INPUT_BLUR = 'INPUT_BLUR';
export const FORM_INPUT_UPDATE = 'FORM_INPUT_UPDATE';

// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATE = 'AUTHENTICATE';

// CLIENT
export const SET_CLIENTS = 'SET_CLIENTS';

// EMPLOYEE
export const SET_EMPLOYEES = 'SET_EMPLOYEES';

// PIPELINE
export const SET_PIPELINES = 'SET_PIPELINES';

// REQUEST
export const SET_REQUESTS = 'SET_REQUESTS';

// PROPOSAL
export const SET_PROPOSALS = 'SET_PROPOSALS';

// PROSPECT
export const SET_PROSPECTS = 'SET_PROSPECTS';

// RENEWAL
export const SET_RENEWALS = 'SET_RENEWALS';

// ACCEPTANCE
export const SET_ACCEPTANCES = 'SET_ACCEPTANCES';

// RELEASE
export const SET_RELEASES = 'SET_RELEASES';

// PLACING
export const SET_PLACINGS = 'SET_PLACINGS';

// QUOTATION
export const SET_QUOTATIONS = 'SET_QUOTATIONS';

// REIMBURSEMENT
export const SET_REIMBURSEMENTS = 'SET_REIMBURSEMENTS';

// CASHLESS
export const SET_CASHLESSES = 'SET_CASHLESSES';

// TIMESHEET
export const SET_TIMESHEETS = 'SET_TIMESHEETS';